version: '3'
services:
  grafana:
    image: grafana/grafana:6.2.2
    ports:
      - "4000:3000"
    links:
      - "influxdb:influxdb"
    volumes:
      - ./grafana/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/UserServiceDashboard.json:/var/lib/grafana/dashboards/UserService.json
      - ./grafana/EventServiceDashboard.json:/var/lib/grafana/dashboards/EventService.json
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - "influxdb"
    restart: on-failure
    networks:
      - int-dev-net

  influxdb:
    image: influxdb:1.7.6
    ports:
      - "8086:8086"
    volumes:
      - ./entrypoint/infulx-entrypoint/influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql/
      - ./volumes/infux-data:/var/lib/influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: secret
    restart: on-failure
    networks:
      - int-dev-net

networks:
  int-dev-net:
    driver: bridge
